[package]
name = "lor-os"
version = "0.1.0"
edition = "2021"

#[build]
#target = "x86_64-lor_os.json"

[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

#[unstable]
#build-std-features = ["compiler-builtins-mem"]
#build-std = ["core", "compiler_builtins"]
